use std::fmt::Write;

use crate::models::deployment::{DeploymentMode, DeploymentProfile, RouterProvider};
use crate::services::gpu_arch::get_combined_arch_list;
use crate::services::GpuArchInfo;

/// Generate a complete launch script from a deployment profile.
pub fn generate_launch_script(
    profile: &DeploymentProfile,
    gpu_archs: &[GpuArchInfo],
    date: &str,
) -> String {
    let mut script = String::new();

    writeln!(script, "#!/bin/bash").unwrap();
    writeln!(script, "# Generated by LLLMMan on {}", date).unwrap();
    writeln!(script, "# Mode: {}", profile.mode.label()).unwrap();

    if !gpu_archs.is_empty() {
        let gpu_descs: Vec<String> = gpu_archs
            .iter()
            .map(|a| format!("{} ({})", a.name, a.sm_string))
            .collect();
        writeln!(script, "# GPUs: {}", gpu_descs.join(", ")).unwrap();
    }

    writeln!(script).unwrap();
    writeln!(script, "set -e").unwrap();
    writeln!(script).unwrap();

    match profile.mode {
        DeploymentMode::SingleGpu => {
            generate_single_gpu_section(&mut script, profile);
        }
        DeploymentMode::DataParallel | DeploymentMode::MultiInstance => {
            generate_multi_instance_section(&mut script, profile, gpu_archs);
            generate_router_section(&mut script, profile);
        }
        DeploymentMode::PipelineParallel => {
            generate_pipeline_parallel_section(&mut script, profile);
        }
    }

    writeln!(script).unwrap();
    writeln!(script, "wait").unwrap();

    script
}

fn generate_single_gpu_section(script: &mut String, profile: &DeploymentProfile) {
    if let Some(instance) = profile.instances.first() {
        let gpu_list: Vec<String> = instance.gpu_indices.iter().map(|i| i.to_string()).collect();

        writeln!(script, "# ============================================================").unwrap();
        writeln!(script, "# Launch Single Instance").unwrap();
        writeln!(script, "# ============================================================").unwrap();

        if !profile.env_overrides.is_empty() {
            writeln!(script).unwrap();
            writeln!(script, "# Environment overrides").unwrap();
            for (key, value) in &profile.env_overrides {
                writeln!(script, "export {}=\"{}\"", key, value).unwrap();
            }
        }

        writeln!(script).unwrap();
        writeln!(script, "echo \"Starting instance on GPU {}...\"", gpu_list.join(",")).unwrap();

        match instance.provider.as_str() {
            "vllm" => {
                writeln!(script, "CUDA_VISIBLE_DEVICES={} vllm serve {} \\", gpu_list.join(","), instance.model_path).unwrap();
                writeln!(script, "  --port {} \\", instance.port).unwrap();
                writeln!(script, "  --gpu-memory-utilization {} \\", instance.memory_utilization).unwrap();
                if let Some(max_seqs) = instance.max_num_seqs {
                    writeln!(script, "  --max-num-seqs {} \\", max_seqs).unwrap();
                }
                writeln!(script, "  --host 0.0.0.0 &").unwrap();
            }
            "sglang" => {
                writeln!(script, "CUDA_VISIBLE_DEVICES={} python -m sglang.launch_server \\", gpu_list.join(",")).unwrap();
                writeln!(script, "  --model-path {} \\", instance.model_path).unwrap();
                writeln!(script, "  --port {} \\", instance.port).unwrap();
                writeln!(script, "  --mem-fraction-static {} \\", instance.memory_utilization).unwrap();
                writeln!(script, "  --host 0.0.0.0 &").unwrap();
            }
            "llama.cpp" => {
                writeln!(script, "CUDA_VISIBLE_DEVICES={} llama-server \\", gpu_list.join(",")).unwrap();
                writeln!(script, "  --model {} \\", instance.model_path).unwrap();
                writeln!(script, "  --port {} \\", instance.port).unwrap();
                writeln!(script, "  --ctx-size {} &", instance.context_size).unwrap();
            }
            _ => {
                writeln!(script, "# Unknown provider: {}", instance.provider).unwrap();
            }
        }
    }
}

fn generate_multi_instance_section(script: &mut String, profile: &DeploymentProfile, gpu_archs: &[GpuArchInfo]) {
    let is_heterogeneous = gpu_archs.len() > 1
        && gpu_archs
            .iter()
            .filter_map(|a| a.compute_capability)
            .collect::<std::collections::HashSet<_>>()
            .len() > 1;

    writeln!(script, "# ============================================================").unwrap();
    writeln!(script, "# Environment Setup").unwrap();
    writeln!(script, "# ============================================================").unwrap();

    if is_heterogeneous {
        let arch_list = get_combined_arch_list(gpu_archs);
        writeln!(script, "export TORCH_CUDA_ARCH_LIST=\"{}\"", arch_list).unwrap();
        writeln!(script, "export FORCE_CUDA=1").unwrap();
        writeln!(script, "export VLLM_SKIP_P2P_CHECK=1").unwrap();
    }

    for (key, value) in &profile.env_overrides {
        writeln!(script, "export {}=\"{}\"", key, value).unwrap();
    }

    writeln!(script).unwrap();
    writeln!(script, "# ============================================================").unwrap();
    writeln!(script, "# Launch Instances").unwrap();
    writeln!(script, "# ============================================================").unwrap();

    for (i, instance) in profile.instances.iter().enumerate() {
        let gpu_idx = instance.gpu_indices.first().copied().unwrap_or(0);
        let gpu_name = gpu_archs.iter().find(|a| a.index == gpu_idx).map(|a| a.name.as_str()).unwrap_or("unknown");

        writeln!(script).unwrap();
        writeln!(script, "# Instance #{}: {} (GPU {})", i + 1, gpu_name, gpu_idx).unwrap();
        writeln!(script, "echo \"Starting instance #{} on GPU {} ({})...\"", i + 1, gpu_idx, gpu_name).unwrap();

        match instance.provider.as_str() {
            "vllm" => {
                let enforce_eager = if is_heterogeneous { "  --enforce-eager \\" } else { "" };
                writeln!(script, "CUDA_VISIBLE_DEVICES={} vllm serve {} \\", gpu_idx, instance.model_path).unwrap();
                writeln!(script, "  --port {} \\", instance.port).unwrap();
                writeln!(script, "  --gpu-memory-utilization {} \\", instance.memory_utilization).unwrap();
                if let Some(max_seqs) = instance.max_num_seqs {
                    writeln!(script, "  --max-num-seqs {} \\", max_seqs).unwrap();
                }
                if !enforce_eager.is_empty() {
                    writeln!(script, "{}", enforce_eager).unwrap();
                }
                writeln!(script, "  --host 0.0.0.0 &").unwrap();
            }
            "sglang" => {
                let disable_cuda_graph = if is_heterogeneous { " --disable-cuda-graph" } else { "" };
                writeln!(script, "CUDA_VISIBLE_DEVICES={} python -m sglang.launch_server \\", gpu_idx).unwrap();
                writeln!(script, "  --model-path {} \\", instance.model_path).unwrap();
                writeln!(script, "  --port {} \\", instance.port).unwrap();
                writeln!(script, "  --mem-fraction-static {}{} \\", instance.memory_utilization, disable_cuda_graph).unwrap();
                writeln!(script, "  --host 0.0.0.0 &").unwrap();
            }
            "llama.cpp" => {
                writeln!(script, "CUDA_VISIBLE_DEVICES={} llama-server \\", gpu_idx).unwrap();
                writeln!(script, "  --model {} \\", instance.model_path).unwrap();
                writeln!(script, "  --port {} \\", instance.port).unwrap();
                writeln!(script, "  --ctx-size {} &", instance.context_size).unwrap();
            }
            _ => {
                writeln!(script, "# Unknown provider: {}", instance.provider).unwrap();
            }
        }
    }

    writeln!(script).unwrap();
    writeln!(script, "# Wait for instances to start").unwrap();
    writeln!(script, "sleep 10").unwrap();
}

fn generate_router_section(script: &mut String, profile: &DeploymentProfile) {
    if let Some(router) = &profile.router_config {
        writeln!(script).unwrap();
        writeln!(script, "# ============================================================").unwrap();
        writeln!(script, "# Launch Router").unwrap();
        writeln!(script, "# ============================================================").unwrap();

        let worker_urls = router.worker_urls.join(" ");

        match router.provider {
            RouterProvider::SglangRouter => {
                writeln!(script, "echo \"Starting SGLang Router on port {}...\"", router.router_port).unwrap();
                writeln!(script, "python -m sglang_router.launch_router \\").unwrap();
                writeln!(script, "  --worker-urls {} \\", worker_urls).unwrap();
                writeln!(script, "  --port {} \\", router.router_port).unwrap();
                writeln!(script, "  --host 0.0.0.0 \\",).unwrap();
                writeln!(script, "  --policy {:?} &", router.policy).unwrap();
            }
            RouterProvider::Nginx => {
                writeln!(script, "# Nginx router configuration not auto-generated.").unwrap();
                writeln!(script, "# Please configure nginx manually with upstream block:").unwrap();
                for url in &router.worker_urls {
                    writeln!(script, "#   server {};", url).unwrap();
                }
            }
            RouterProvider::Custom => {
                writeln!(script, "# Custom router: configure manually.").unwrap();
            }
        }

        writeln!(script).unwrap();
        writeln!(script, "echo \"Setup complete!\"").unwrap();
        writeln!(script, "echo \"  Router: http://localhost:{}/v1/chat/completions\"", router.router_port).unwrap();
        for (i, url) in router.worker_urls.iter().enumerate() {
            writeln!(script, "echo \"  Instance #{}: {}\"", i + 1, url).unwrap();
        }
    }
}

fn generate_pipeline_parallel_section(script: &mut String, profile: &DeploymentProfile) {
    if let Some(instance) = profile.instances.first() {
        let gpu_count = instance.gpu_indices.len();

        writeln!(script, "# ============================================================").unwrap();
        writeln!(script, "# Pipeline Parallel Launch").unwrap();
        writeln!(script, "# ============================================================").unwrap();

        if !profile.env_overrides.is_empty() {
            writeln!(script).unwrap();
            for (key, value) in &profile.env_overrides {
                writeln!(script, "export {}=\"{}\"", key, value).unwrap();
            }
        }

        writeln!(script).unwrap();
        writeln!(script, "echo \"Starting pipeline parallel on {} GPUs...\"", gpu_count).unwrap();

        match instance.provider.as_str() {
            "vllm" => {
                writeln!(script, "vllm serve {} \\", instance.model_path).unwrap();
                writeln!(script, "  --port {} \\", instance.port).unwrap();
                writeln!(script, "  --pipeline-parallel-size {} \\", gpu_count).unwrap();
                writeln!(script, "  --gpu-memory-utilization {} \\", instance.memory_utilization).unwrap();
                writeln!(script, "  --enforce-eager \\").unwrap();
                writeln!(script, "  --host 0.0.0.0 &").unwrap();
            }
            "sglang" => {
                writeln!(script, "# SGLang pipeline parallel not yet fully supported.").unwrap();
                writeln!(script, "# Use vLLM for pipeline parallel setups.").unwrap();
            }
            _ => {
                writeln!(script, "# Pipeline parallel only supported for vLLM.").unwrap();
            }
        }
    }
}

/// Generate a summary of what the script will do.
pub fn generate_script_summary(profile: &DeploymentProfile, gpu_archs: &[GpuArchInfo]) -> String {
    let mut summary = String::new();

    writeln!(summary, "Mode: {}", profile.mode.label()).unwrap();
    writeln!(summary, "Instances: {}", profile.instances.len()).unwrap();

    for (i, instance) in profile.instances.iter().enumerate() {
        let gpu_list: Vec<&str> = instance.gpu_indices.iter().map(|i| {
            gpu_archs.iter().find(|a| a.index == *i).map(|a| a.name.as_str()).unwrap_or("unknown")
        }).collect();
        writeln!(summary, "  Instance #{}: GPU {} ({}) on port {}", i + 1, instance.gpu_indices.iter().map(|i| i.to_string()).collect::<Vec<_>>().join(","), gpu_list.join(","), instance.port).unwrap();
    }

    if let Some(router) = &profile.router_config {
        writeln!(summary, "Router: {} on port {} (policy: {:?})", router.provider.label(), router.router_port, router.policy).unwrap();
    }

    summary
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::deployment::generate_default_profile;
    use crate::models::GpuTier;

    fn make_test_gpus() -> Vec<GpuArchInfo> {
        vec![
            GpuArchInfo {
                index: 0,
                name: "RTX 3090".to_string(),
                compute_capability: Some((8, 6)),
                sm_string: "sm_86".to_string(),
                vram_mb: 24 * 1024,
                performance_tier: GpuTier::Mid,
            },
            GpuArchInfo {
                index: 1,
                name: "RTX PRO 6000".to_string(),
                compute_capability: Some((12, 0)),
                sm_string: "sm_120".to_string(),
                vram_mb: 96 * 1024,
                performance_tier: GpuTier::Ultra,
            },
        ]
    }

    #[test]
    fn test_generate_single_gpu_script() {
        let profile = generate_default_profile(DeploymentMode::SingleGpu, "vllm", "model", 1);
        let script = generate_launch_script(&profile, &make_test_gpus(), "2026-05-17");

        assert!(script.contains("#!/bin/bash"));
        assert!(script.contains("vllm serve"));
        assert!(script.contains("--port 8080"));
        assert!(script.contains("wait"));
    }

    #[test]
    fn test_generate_multi_instance_script() {
        let profile = generate_default_profile(DeploymentMode::MultiInstance, "vllm", "model", 2);
        let script = generate_launch_script(&profile, &make_test_gpus(), "2026-05-17");

        assert!(script.contains("TORCH_CUDA_ARCH_LIST"));
        assert!(script.contains("VLLM_SKIP_P2P_CHECK=1"));
        assert!(script.contains("--enforce-eager"));
        assert!(script.contains("CUDA_VISIBLE_DEVICES=0"));
        assert!(script.contains("CUDA_VISIBLE_DEVICES=1"));
        assert!(script.contains("sglang_router.launch_router"));
    }

    #[test]
    fn test_generate_sglang_multi_instance_script() {
        let profile = generate_default_profile(DeploymentMode::MultiInstance, "sglang", "model", 2);
        let script = generate_launch_script(&profile, &make_test_gpus(), "2026-05-17");

        assert!(script.contains("sglang.launch_server"));
        assert!(script.contains("--disable-cuda-graph"));
        assert!(script.contains("sglang_router.launch_router"));
    }

    #[test]
    fn test_generate_pipeline_parallel_script() {
        let profile = generate_default_profile(DeploymentMode::PipelineParallel, "vllm", "model", 4);
        let script = generate_launch_script(&profile, &make_test_gpus(), "2026-05-17");

        assert!(script.contains("--pipeline-parallel-size 4"));
        assert!(script.contains("--enforce-eager"));
    }

    #[test]
    fn test_generate_script_summary() {
        let profile = generate_default_profile(DeploymentMode::MultiInstance, "vllm", "model", 3);
        let summary = generate_script_summary(&profile, &make_test_gpus());

        assert!(summary.contains("Mode: Multi-Instance"));
        assert!(summary.contains("Instances: 3"));
        assert!(summary.contains("Router"));
    }

    #[test]
    fn test_script_contains_set_e() {
        let profile = generate_default_profile(DeploymentMode::SingleGpu, "vllm", "model", 1);
        let script = generate_launch_script(&profile, &make_test_gpus(), "2026-05-17");
        assert!(script.contains("set -e"));
    }
}
